FROM eclipse-temurin:17-jre

ADD target/spring-otlp-tracing-profiling-*-SNAPSHOT.jar /app.jar
ADD target/opentelemetry-javaagent-*.jar /opentelemetry-javaagent.jar

ENV OTEL_TRACES_EXPORTER="otlp"
ENV OTEL_METRICS_EXPORTER="none"
ENV OTEL_LOGS_EXPORTER="none"

ENTRYPOINT java -jar -javaagent:/opentelemetry-javaagent.jar app.jar
